/** Standard HTTP error codes — ERROR_HANDLING.md §2 */
export const STANDARD_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type StandardErrorCode =
  (typeof STANDARD_ERROR_CODES)[keyof typeof STANDARD_ERROR_CODES];

export const HTTP_STATUS_TO_ERROR_CODE: Record<number, StandardErrorCode> = {
  400: STANDARD_ERROR_CODES.VALIDATION_ERROR,
  401: STANDARD_ERROR_CODES.UNAUTHENTICATED,
  403: STANDARD_ERROR_CODES.FORBIDDEN,
  404: STANDARD_ERROR_CODES.NOT_FOUND,
  409: STANDARD_ERROR_CODES.CONFLICT,
  429: STANDARD_ERROR_CODES.RATE_LIMITED,
  500: STANDARD_ERROR_CODES.INTERNAL_ERROR,
};
