import type { CustomFieldEntityType, CustomFieldType, DocumentScope } from '@hrm/shared-types';

export type BuilderEntityType = Exclude<CustomFieldEntityType, 'document'>;

/**
 * User-facing strings for the document type admin and the custom field builder.
 * Kept in one catalogue so they can move into the i18n layer without touching components.
 */
export const customFieldsCopy = {
  fieldTypes: {
    text: { label: 'Text', hint: 'Short free-text answer' },
    number: { label: 'Number', hint: 'Numeric value' },
    date: { label: 'Date', hint: 'Calendar date' },
    dropdown: { label: 'Dropdown', hint: 'Pick one option from a list' },
    checkbox: { label: 'Checkbox', hint: 'Yes / no' },
    radio: { label: 'Radio', hint: 'Pick one visible option' },
    file: { label: 'File', hint: 'Upload any file' },
    image: { label: 'Image', hint: 'Upload a photo or scan' },
    signature: { label: 'Signature', hint: 'Drawn or typed signature' },
  } satisfies Record<CustomFieldType, { label: string; hint: string }>,

  editor: {
    addField: 'Add field',
    fieldLabel: 'Label',
    fieldLabelPlaceholder: 'e.g. Passport number',
    fieldType: 'Type',
    fieldKey: 'Key',
    fieldKeyHint: 'Generated from the label and fixed once saved, so stored values stay linked.',
    newKeyPreview: (key: string) => (key ? `Will be saved as ${key}` : 'Enter a label to generate the key'),
    required: 'Required',
    active: 'Active',
    activeHint: 'Inactive fields are hidden from forms but keep values already stored.',
    inactive: 'Inactive',
    optional: 'Optional',
    options: 'Options',
    optionsPlaceholder: 'Type an option and press Enter',
    optionsAdd: 'Add',
    removeOption: (option: string) => `Remove option ${option}`,
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove field',
    expand: 'Edit field',
    collapse: 'Collapse field',
    untitled: 'Untitled field',
    noFields: 'No fields yet. Add the information this document should capture.',
    typeLocked:
      'Type is locked because documents already store values for this field. Add a new field instead.',
    removeWarning:
      'Documents already use this type. Removing a field hides its stored values; mark it inactive to retire it instead.',
  },

  validation: {
    labelRequired: 'Label is required.',
    labelNeedsCharacters: 'Label must contain letters or numbers.',
    optionsRequired: 'Add at least one option.',
    duplicateKey: (key: string) => `Another field already uses the key "${key}".`,
    nameRequired: 'Name is required.',
    fixErrors: 'Fix the highlighted fields before saving.',
  },

  preview: {
    title: 'Form preview',
    description: 'How the fields appear when someone fills this in.',
    empty: 'Active fields will appear here.',
    choose: 'Select…',
    upload: 'Click to upload',
    signHere: 'Sign here',
    expiryDate: 'Expiry date',
    yes: 'Yes',
  },

  documentTypes: {
    title: 'Document types',
    description:
      'Define the documents your company collects and the information each one captures.',
    add: 'Add document type',
    searchPlaceholder: 'Search document types…',
    loadError: 'Could not load document types.',
    emptyTitle: 'No document types yet',
    emptyDescription: 'Create types like Passport, NID or Contract and choose the fields each one needs.',
    noMatches: 'No document types match your search.',
    columns: {
      name: 'Name',
      scope: 'Scope',
      fields: 'Fields',
      rules: 'Rules',
      documents: 'Documents',
      status: 'Status',
    },
    scopes: {
      employee: { label: 'Employee', description: 'Uploaded per employee (e.g. passport, NID).' },
      company: { label: 'Company-wide', description: 'One record for the whole company (e.g. trade licence).' },
    } satisfies Record<DocumentScope, { label: string; description: string }>,
    verification: 'Verification',
    verificationHint: 'Uploads stay pending until an admin verifies them.',
    expiry: 'Expiry tracking',
    expiryHint: 'Uploads need an expiry date and trigger expiry reminders.',
    active: 'Active',
    activeHint: 'Inactive types cannot receive new uploads.',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    fieldCount: (n: number) => `${n} field${n === 1 ? '' : 's'}`,
    documentCount: (n: number) => `${n} uploaded`,
    noFields: 'No fields',
    edit: 'Edit',
    activate: 'Activate',
    deactivate: 'Deactivate',
    delete: 'Delete',
    deleteBlocked: 'Documents have been uploaded for this type. Deactivate it instead.',
    deleteTitle: 'Delete document type?',
    deleteDescription: (name: string) => `"${name}" and its field definitions will be permanently removed.`,
    createTitle: 'New document type',
    editTitle: (name: string) => `Edit ${name}`,
    editorDescription: 'Details, rules and the fields captured on upload.',
    detailsSection: 'Details',
    fieldsSection: 'Fields',
    name: 'Name',
    namePlaceholder: 'e.g. Passport',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Optional guidance shown to admins',
    scope: 'Scope',
    inUseNotice: (n: number) =>
      `${n} document${n === 1 ? ' uses' : 's use'} this type. Existing field types are locked so stored values stay valid.`,
    cancel: 'Cancel',
    create: 'Create type',
    save: 'Save changes',
    saving: 'Saving…',
    saveError: 'Could not save the document type.',
    partialSaveError: 'Details were saved, but the fields could not be updated.',
    toggleError: 'Could not update the status.',
  },

  customFields: {
    title: 'Custom field builder',
    description: 'Add your own fields to employees, departments and other records.',
    add: 'Add field',
    loadError: 'Could not load custom fields.',
    entities: {
      employee: { label: 'Employee', description: 'Extra details on each employee profile.' },
      company: { label: 'Company', description: 'Extra details on the company record.' },
      department: { label: 'Department', description: 'Extra details on each department.' },
      designation: { label: 'Designation', description: 'Extra details on each designation.' },
      contract: { label: 'Contract', description: 'Extra details on employment contracts.' },
      candidate: { label: 'Candidate', description: 'Extra details captured for recruitment candidates.' },
    } satisfies Record<BuilderEntityType, { label: string; description: string }>,
    fieldsFor: (entity: string) => `${entity} fields`,
    emptyTitle: (entity: string) => `No ${entity.toLowerCase()} fields yet`,
    emptyDescription: 'Fields you add here extend the standard form with your own information.',
    required: 'Required',
    optional: 'Optional',
    edit: 'Edit',
    delete: 'Delete',
    moveUp: 'Move up',
    moveDown: 'Move down',
    toggleActive: (label: string) => `Toggle ${label} active`,
    createTitle: (entity: string) => `New ${entity.toLowerCase()} field`,
    editTitle: (label: string) => `Edit ${label}`,
    modalDescription: 'Configure how this field is captured.',
    deleteTitle: 'Delete field?',
    deleteDescription: (label: string) =>
      `"${label}" will be permanently removed. To keep values already captured, mark it inactive instead.`,
    cancel: 'Cancel',
    create: 'Create field',
    save: 'Save changes',
    saving: 'Saving…',
    saveError: 'Could not save the field.',
    reorderError: 'Could not reorder fields.',
    toggleError: 'Could not update the field.',
  },
};
