/**
 * User-facing strings for the payslip screens.
 * Kept in one catalogue so they can move into the i18n layer without touching components.
 */
export const payslipCopy = {
  title: 'Payslips',
  description:
    'Payslips are issued when payroll is finalized. Open any employee’s payslip to view it here or download the PDF.',
  loadError: 'Could not load payslips.',
  allPeriods: 'All payroll periods',
  periodFilter: 'Payroll period',
  searchPlaceholder: 'Search name, ID or department…',
  tabs: {
    all: (n: number) => `All (${n})`,
    issued: (n: number) => `Issued (${n})`,
    missing: (n: number) => `Not generated (${n})`,
  },
  employeeFilter: (name: string) => `Showing payslips for ${name}`,
  clearEmployee: 'Show everyone',
  colEmployee: 'Employee',
  colPeriod: 'Pay period',
  colPayment: 'Payment date',
  colNet: 'Net pay',
  colStatus: 'Payslip',
  issued: 'Issued',
  missing: 'Not generated',
  issuedOn: (date: string) => `Issued ${date}`,
  missingHint: 'Finalization didn’t produce this payslip. Generate it to make it available.',
  view: 'View',
  download: 'Download PDF',
  generate: 'Generate payslip',
  generating: 'Generating…',
  generated: (name: string) => `Payslip generated for ${name}.`,
  emptyTitle: 'No payslips yet',
  emptyDescription: 'Payslips appear here once a pay run is finalized.',
  emptyAction: 'Go to pay runs',
  noMatchTitle: 'No payslips match',
  noMatchDescription: 'Try another period, search or tab.',
  clearFilters: 'Clear filters',
  viewer: {
    description: (employeeNumber: string, period: string) => `${employeeNumber} · ${period}`,
    gross: 'Gross pay',
    deductions: 'Deductions',
    net: 'Net pay',
    loading: 'Loading payslip…',
    error: 'Could not load this payslip.',
    retry: 'Try again',
    openTab: 'Open in new tab',
    previous: 'Previous payslip',
    next: 'Next payslip',
    position: (index: number, total: number) => `${index} of ${total}`,
    frameTitle: (name: string) => `Payslip PDF for ${name}`,
  },
} as const;
