import type { PermissionAction } from '@hrm/shared-types';

/**
 * User-facing strings for the roles & permissions screens.
 * Kept in one catalogue so they can move into the i18n layer without touching components.
 */
export const rolesCopy = {
  eyebrow: 'Settings',
  title: 'Roles & Permissions',
  description:
    'Every user holds one role. A role grants actions on modules — the default roles are fixed, and you can build custom roles from the same permissions.',
  views: {
    label: 'Roles views',
    roles: 'Roles',
    matrix: 'Matrix overview',
  },
  loadError: 'Could not load roles.',
  retry: 'Try again',
  dismiss: 'Dismiss',
  newRole: 'New custom role',
  searchPlaceholder: 'Search roles…',
  defaultRoles: 'Default roles',
  customRoles: 'Custom roles',
  noCustomRoles: 'No custom roles yet.',
  noMatch: 'No roles match your search.',
  users: (n: number) => `${n.toLocaleString()} ${n === 1 ? 'user' : 'users'}`,
  grants: (n: number) => `${n} ${n === 1 ? 'permission' : 'permissions'}`,
  badges: {
    system: 'Default',
    custom: 'Custom',
    yours: 'Your role',
  },
  scope: {
    team: 'Own team',
    self: 'Self only',
    teamHint: 'Limited to their direct and indirect reports.',
    selfHint: 'Limited to their own records.',
    fieldLabel: 'Data access',
    options: {
      all: 'Company-wide',
      team: 'Own reporting line',
    },
    fieldHint: 'Own reporting line limits employee records, requests and approvals to the holder’s direct and indirect reports.',
    notHeld: 'Only company-wide roles can grant company-wide access.',
    changed: (from: string, to: string) => `Data access changed from ${from} to ${to}.`,
  },
  systemRoleDescriptions: {
    'Super Admin': 'Platform-level: manages tenants and billing, not company data.',
    'Company Owner': 'Full access within the company.',
    'HR Admin': 'Runs people operations — employees, leave, attendance and HR settings.',
    'Payroll Admin': 'Runs payroll end to end, through approval and finalization.',
    Manager: 'Approves requests and sees records for their own team.',
    Employee: 'Self-service access to their own records.',
    Accountant: 'Reviews and approves payroll and contractor payments.',
    Recruiter: 'Manages hiring and new-employee records.',
  } as Record<string, string>,
  customRoleDescription: 'Company-defined role.',
  editor: {
    readOnlyTitle: 'Default roles can’t be changed',
    readOnlyBody: 'Duplicate this role to start a custom role with the same permissions.',
    duplicate: 'Duplicate as custom role',
    nameLabel: 'Role name',
    module: 'Module',
    allActions: 'All',
    rowToggle: (module: string) => `Grant every ${module} action`,
    columnToggle: (action: string) => `Grant ${action} on every module`,
    notUsed: 'Not used by this module',
    notUsedButGranted: 'Granted, but nothing in this module checks this action yet.',
    notHeld: 'You can only grant permissions you hold yourself.',
    viewRequired: 'Other actions need View, so it is added automatically.',
    platformGroup: 'Platform (read-only)',
    save: 'Save changes',
    create: 'Create role',
    discard: 'Discard',
    saving: 'Saving…',
    unsaved: (added: number, removed: number) =>
      [added ? `${added} added` : '', removed ? `${removed} removed` : ''].filter(Boolean).join(', '),
    renamedOnly: 'Name changed',
    omitted: (n: number) =>
      `${n === 1 ? '1 permission' : `${n} permissions`} from the template ${n === 1 ? 'was' : 'were'} left out — you can only grant permissions you hold yourself.`,
    delete: 'Delete role',
    deleteBlocked: (users: number) => `Assigned to ${users === 1 ? '1 user' : `${users} users`} — move them to another role first.`,
    selfWarning: 'This is your own role. You keep Settings view and edit so you can’t lock yourself out.',
    propagation:
      'Changes reach signed-in users when their session refreshes (within about 15 minutes). Approve and finalize are always re-checked immediately.',
    nameRequired: 'Enter a role name.',
    nameTooShort: 'Use at least 2 characters.',
    nameTooLong: 'Use 100 characters or fewer.',
    nameReserved: 'That name belongs to a default role.',
    nameTaken: 'Another role already uses this name.',
    permissionRequired: 'Grant at least one permission.',
    saved: (name: string) => `Saved ${name}.`,
    created: (name: string) => `Created ${name}.`,
    deleted: (name: string) => `Deleted ${name}.`,
    discardConfirm: 'You have unsaved changes. Discard them?',
  },
  create: {
    title: 'New custom role',
    description: 'Name the role and choose a starting point. You can adjust every permission before saving.',
    startFrom: 'Start from',
    blank: 'No permissions',
    copyOf: (name: string) => `Copy of ${name}`,
    continue: 'Continue',
    cancel: 'Cancel',
    placeholder: 'e.g. Payroll Officer',
  },
  review: {
    title: (name: string) => `Save changes to ${name}?`,
    createTitle: (name: string) => `Create ${name}?`,
    affects: (n: number) =>
      n === 0 ? 'No users hold this role yet.' : `${n === 1 ? '1 user holds' : `${n.toLocaleString()} users hold`} this role and will be affected.`,
    added: 'Granted',
    removed: 'Revoked',
    renamed: (from: string, to: string) => `Renamed from “${from}” to “${to}”.`,
    sensitive: 'Includes approve or finalize — these allow committing financial and HR decisions.',
    confirm: 'Save role',
    confirmCreate: 'Create role',
    cancel: 'Keep editing',
  },
  deleteDialog: {
    title: (name: string) => `Delete ${name}?`,
    body: 'The role and its permissions are removed. This can’t be undone.',
    confirm: 'Delete role',
    cancel: 'Cancel',
  },
  matrix: {
    description: 'Each cell lists the actions a role holds on that module, in the format of ROLES_PERMISSIONS.md §3. Select a role to edit it.',
    role: 'Role',
    none: '—',
    exportCsv: 'Export CSV',
    scopeSuffix: { team: 'own team', self: 'self' },
  },
  modules: {
    employee: { label: 'Employees', description: 'Employee records, profiles and lifecycle events' },
    leave: { label: 'Leave', description: 'Leave requests, balances and policies' },
    attendance: { label: 'Attendance', description: 'Clock-ins, timesheets, rosters and attendance reports' },
    payroll: { label: 'Payroll', description: 'Pay runs, salary structures, payslips and payroll reports' },
    contractors: { label: 'Contractors', description: 'Contractor records, invoices and payments' },
    recruitment: { label: 'Recruitment', description: 'Requisitions, candidates and offers' },
    performance: { label: 'Performance', description: 'Reviews, goals and 360° feedback' },
    training: { label: 'Training', description: 'Courses and enrolments' },
    engagement: { label: 'Engagement', description: 'Surveys, kudos and announcements' },
    employee_relations: { label: 'Employee relations', description: 'HR cases and grievances' },
    health_safety: { label: 'Health & safety', description: 'Workplace incidents and inspections' },
    support: { label: 'Support', description: 'Help-desk tickets and knowledge base' },
    settings: { label: 'Settings', description: 'Company setup, roles, workflows and integrations' },
    audit: { label: 'Audit & security', description: 'Audit logs and security settings' },
    tenant: { label: 'Billing & subscription', description: 'Tenant billing — Super Admin only' },
    platform: { label: 'Platform administration', description: 'Tenant management — Super Admin only' },
  } as Record<string, { label: string; description: string }>,
  moduleGroups: {
    people: 'People & time',
    payroll: 'Payroll',
    talent: 'Talent',
    experience: 'Employee experience',
    admin: 'Administration',
  },
  actions: {
    view: 'View',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    approve: 'Approve',
    finalize: 'Finalize',
  } satisfies Record<PermissionAction, string>,
  actionHints: {
    'payroll:edit': 'Includes calculating pay runs.',
    'payroll:finalize': 'Locks pay runs and issues payslips.',
  } as Record<string, string>,
} as const;
